### ISSUE TITLE
Failed to update tool 'ladeak.chttp'

### ISSUE THREAD

**Issue by juniorjse** [ladeak/Http3Tools#3]
The settings file in the tool's NuGet package is invalid: The settings file 'DotnetToolSettings.xml' was not found in the package.
Unable to install tool 'ladeak.chttp'. Please contact the author for assistance.

**Comment by ladeak** [comment]
Could you share which .NET SDK are you using?

**Comment by ladeak** [comment]
Could you try using .NET 9 SDK with version 3.0.1-prerelease-01 or use version 2.3.0 with .NET 8 SDK?

**Comment by ladeak** [comment]
I would suggest using the binaries from the release page instead: https://github.com/ladeak/Http3Tools/releases
